version: '3.3'
services:
  todo-rest-api:
    image: 162997/employeeinformation:0.0.1-SNAPSHOT
    ports:
    - 5001:5000
    restart: always
    depends_on: 
      -mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: todos-user
      RDS_PASSWORD: dummytodos
  mysql:
    image: mysql:5.7
    ports:
    - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: todos