version: '3.3'
services:
  employeeinformation:
    image: 162997/employeeinformation:0.0.1-SNAPSHOT
    ports:
    - 5001:5000
    restart: always
    depends_on: 
      -mysql
    environment:
      RDS_HOSTNAME: employee-information.mysql.database.azure.com
      RDS_PORT: 3306
      RDS_DB_NAME: AzureDB
      RDS_USERNAME: totosuser@employee-information
      RDS_PASSWORD: todouser@123
  mysql:
    image: mysql:5.7
    ports:
    - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: todouser@123
      MYSQL_USER: totosuser@employee-information
      MYSQL_PASSWORD: todouser@123
      MYSQL_DATABASE: AzureDB